### ISSUE TITLE
Error parsing attachments with regex reserved chars in the filename

### ISSUE THREAD

**Issue by andersonjohnf** [bbottema/outlook-message-parser#33]
https://github.com/bbottema/outlook-message-parser/blob/34ecabbc90bb61fc43e46cbaa40e12688f94db85/src/main/java/org/simplejavamail/outlookmessageparser/model/OutlookMessage.java#L328

Example filename: [01-06-2020 09.00.14]1 - Patch Compliance.PDF

Error:
java.util.regex.PatternSyntaxException: Illegal character range near index 13
cid:['"]?[01-06-2020 09.00.14]1 - Patch Compliance.PDF['"]?
             ^] with root cause
java.util.regex.PatternSyntaxException: Illegal character range near index 13
cid:['"]?[01-06-2020 09.00.14]1 - Patch Compliance.PDF['"]?
             ^
        at java.util.regex.Pattern.error(Pattern.java:1957)
        at java.util.regex.Pattern.range(Pattern.java:2657)
        at java.util.regex.Pattern.clazz(Pattern.java:2564)
        at java.util.regex.Pattern.sequence(Pattern.java:2065)
        at java.util.regex.Pattern.expr(Pattern.java:1998)
        at java.util.regex.Pattern.compile(Pattern.java:1698)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at org.simplejavamail.outlookmessageparser.model.OutlookMessage.htmlContainsCID(OutlookMessage.java:343)

**Comment by andersonjohnf** [comment]
A super simple "fix" is just to wrap in a try/catch and return false on error

**Comment by KacperFKorban** [comment]
This should be fixed by #30

**Comment by bbottema** [comment]
Fix for #30 has been released in 1.7.5
